language: swift
swift:
 - 3.3
xcode_project: WRUW-FM.xcworkspace # path to your xcodeproj folder
xcode_scheme: WRUW-FMTests
osx_image: xcode9.3

install:
 - gem install cocoapods-keys
 - pod keys set "MixpanelToken" "-"
