language: swift
swift:
 - 3.3
xcode_project: WRUW-FM.xcworkspace # path to your xcodeproj folder
xcode_scheme: WRUW-FMTests
osx_image: xcode9.3
script:
    - xcodebuild clean build -sdk iphonesimulator -workspace WRUW-FM.xcworkspace -scheme WRUW-FMTests CODE_SIGNING_REQUIRED=NO

install:
 - gem install cocoapods-keys
 - pod keys set "MixpanelToken" "-"
