language: swift
swift:
 - 3.3
xcode_project: WRUW-FM.xcworkspace # path to your xcodeproj folder
xcode_scheme: WRUW-FMTests
osx_image: xcode9.3
script:
    - xcodebuild \
        -workspace WRUW-FM.xcworkspace \ 
        -scheme WRUW-FMTests \ 
        -destination 'platform=iOS Simulator,name=iPhone X' \
        test

install:
 - gem install cocoapods-keys
 - pod keys set "MixpanelToken" "-"
