language: swift
swift:
 - 3.3
xcode_project: WRUW-FM.xcworkspace # path to your xcodeproj folder
xcode_scheme: WRUW-FMTests
osx_image: xcode9.3
script:
    - xcodebuild -workspace WRUW-FM.xcworkspace -scheme WRUW-FMTests -destination 'platform=iOS Simulator,name=iPhone X' test

before_install:
  - npm install ios-sim -g
  # Pre-start iPhone 7 + iOS 10.2 simulator
  - ios-sim start --devicetypeid "com.apple.CoreSimulator.SimDeviceType.iPhone-X, 11.3"

install:
 - gem install cocoapods-keys
 - pod keys set "MixpanelToken" "-"
 - pod install
